version: '3'
services:
    mysql:
        hostname: mysql
        container_name: mysql
        image: mysql
        command: mysqld
        restart: always
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        volumes:
            - /home/docker/mysql/data:/var/lib/mysql
            - /home/docker/mysql/conf:/etc/mysql
            - /home/docker/mysql/logs:/var/log/mysql
