version: '3'
services:
    redis:
        hostname: redis
        container_name: redis
        image: redis
        restart: always
        command: redis-server /etc/redis/redis.conf --appendonly yes --requirepass 123456
        ports:
            - "6379:6379"
        volumes:
            - /home/docker/redis/conf:/etc/redis
            - /home/docker/redis/data:/var/lib/redis
            - /home/docker/redis/logs:/var/log/redis